"""Release report generation module for Markdown and JSON exports."""

from __future__ import annotations

import json

from eventgate.domain.history import ReleaseRecord


def generate_markdown_report(record: ReleaseRecord) -> str:
    """Generate a clean, deterministic GitHub-Flavored Markdown report."""
    if record.published:
        pub_status = "PUBLISHED (EventBridge Ingestion Confirmed)"
    elif record.decision == "BLOCK":
        pub_status = "PREVENTED (Gate Enforced Hard Interception)"
    else:
        pub_status = "PREVENTED / NOT PUBLISHED"

    lines = [
        "# EventGate Release Review Report",
        "",
        f"**Generated:** {record.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}",
        "",
        "## Release Overview",
        "",
        "| Attribute | Value |",
        "| :--- | :--- |",
        f"| **Event Type** | `{record.event_type}` |",
        f"| **Version Transition** | `v{record.current_version}` → `v{record.proposed_version}` |",
        f"| **Environment** | `{record.environment}` |",
        f"| **Compatibility Result** | **{record.compatibility_result}** |",
        f"| **Severity** | `{record.severity}` |",
        f"| **Release Policy** | `{record.policy_name}` |",
        f"| **Policy Reason** | {record.policy_reason} |",
        f"| **Final Decision** | **{record.decision}** |",
        f"| **Publication Status** | {pub_status} |",
        "",
        "## Release Evidence & Traceability",
        "",
        f"- **Record / Analysis ID:** `{record.record_id}`",
        f"- **Request ID:** `{record.request_id or 'N/A'}`",
    ]

    if record.event_id:
        lines.append(f"- **Event ID:** `{record.event_id}`")
    if record.event_bridge_event_id:
        lines.append(f"- **EventBridge Ingestion ID:** `{record.event_bridge_event_id}`")
    if record.published_at:
        lines.append(f"- **Published Timestamp:** `{record.published_at.isoformat()}`")
    if record.error:
        lines.append(f"- **Enforcement Detail:** {record.error}")

    lines.extend([
        "",
        "## Downstream Consumer Impact",
        "",
    ])

    if not record.affected_consumers:
        lines.append(
            "✓ **Zero downstream consumer breaks detected.** "
            "All registered consumers are backward compatible."
        )
    else:
        lines.append(f"⚠️ **{len(record.affected_consumers)} downstream consumer(s) impacted:**")
        for c in record.affected_consumers:
            lines.append(f"- `{c}`")

    if record.findings_summary:
        lines.extend([
            "",
            "## Findings & Schema Diagnostics",
            "",
            "| Consumer | Field | Finding Status | Rule | Expected Type | Proposed Type | Reason |",
            "| :--- | :--- | :--- | :--- | :--- | :--- | :--- |",
        ])
        for f in record.findings_summary:
            cid = f.get("consumerId", f.get("consumer_id", "N/A"))
            field_name = f.get("field", "N/A")
            status = f.get("status", "N/A")
            rule_id = f.get("ruleId", f.get("rule_id", "N/A"))
            expected = f.get("expectedType", f.get("expected_type", "—")) or "—"
            proposed = f.get("proposedType", f.get("proposed_type", "—")) or "—"
            reason = f.get("reason", "—")
            lines.append(
                f"| `{cid}` | `{field_name}` | **{status}** | "
                f"`{rule_id}` | `{expected}` | `{proposed}` | {reason} |"
            )

    lines.extend([
        "",
        "---",
        "*Report generated by PrimeX EventGate Platform. Authoritative audit artifact.*",
        "",
    ])

    return "\n".join(lines)


def generate_json_report(record: ReleaseRecord) -> str:
    """Generate a clean, indented JSON export of the release record."""
    data = record.to_dict()
    return json.dumps(data, indent=2)
